Cada equipe deverá entregar um notebook jupyter (.ipynb) com as análises realizadas. As análises devem apresentar as matrizes de confusão e as métricas de avaliação (acurácia, precisão, recall, F1-score).

As seguintes perguntas devem ser respondidas no próprio notebook:

    Quais algoritmos foram analisados?
    Quais os melhores parâmetros para cada algoritmo?
    Os treinamentos apresentaram overfitting ou underfitting?
    Qual dos três algoritmos teve melhor acurácia?
    Neste problema, é melhor analisar a precisão ou o recall? Qual algoritmo teve melhor comportamento?

In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('winedataset.csv')

df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     0.534709  
std       0.154386     0.169507     1.065668     0.498950  
min       2.740000     0.330000     8.400000     0.000000  
25%       3.210000     0.550000     9.500000     0.000000  
50%       3.310000     0.620000    10.200000     1.000000  
75%       3.400000     0.730000    11.100000     1.000000  
max       4.010000     2.000000    14.900000     1.000000

In [10]:
from sklearn.model_selection import train_test_split

X = df.iloc[:, :-1]
y = df.iloc[:, -1:]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, train_size = .7)

In [21]:
#Applying Logistic Regression Model
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
KNN_Classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KNN_Classifier.fit(X_train, y_train.values.ravel())

y_pred_KNN = KNN_Classifier.predict(X_test)
cm_knn = confusion_matrix(y_test, y_pred_KNN)
print(cm_knn)
accuracy_score(y_test, y_pred_KNN)



[[132  94]
 [ 86 168]]


0.625

In [12]:


from sklearn.tree import DecisionTreeClassifier

Decision_Tree_Classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
Decision_Tree_Classifier.fit(X_train, y_train.values.ravel())
y_pred_DT = Decision_Tree_Classifier.predict(X_test)
cm_dt = confusion_matrix(y_test, y_pred_DT)
print(cm_dt)
accuracy_score(y_test, y_pred_DT)

[[166  60]
 [ 66 188]]


0.7375

In [13]:
from sklearn.ensemble import RandomForestClassifier

RandomForest_Classifier = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 0)
RandomForest_Classifier.fit(X_train, y_train.values.ravel())
y_pred_RF = RandomForest_Classifier.predict(X_test)
cm_rf = confusion_matrix(y_test, y_pred_RF)

print(cm_rf)
accuracy_score(y_test, y_pred_RF)

[[172  54]
 [ 48 206]]


0.7875

In [22]:
from sklearn.metrics import precision_score, recall_score, f1_score

print(precision_score(y_test, y_pred_KNN),
precision_score(y_test, y_pred_DT),
precision_score(y_test, y_pred_RF))

print(recall_score(y_test, y_pred_KNN),
recall_score(y_test, y_pred_DT),
recall_score(y_test, y_pred_RF))

print(f1_score(y_test, y_pred_KNN),
f1_score(y_test, y_pred_DT),
f1_score(y_test, y_pred_RF))

0.6412213740458015 0.7580645161290323 0.7923076923076923
0.6614173228346457 0.7401574803149606 0.8110236220472441
0.6511627906976745 0.749003984063745 0.801556420233463
